sudo apt upgrade (melhoria) 
sudo apt update (atualização)
sudo apt install mysql- server (instalação)
sudo apt install php (instalação)
sudo apt install phpmyadmin (configurar)
sudo apt install apache2 (confirmar programação)
mkdir (criar pasta)
ls (ver pastas)
rm (excluir pasta)
r-m-r 'nome da pasta' (excluir pasta e arquivos)
cd (trocar de pasta)
cd. (mesma pasta)
cd.. (sair do arquivo)
ssh 'usuário'@IP (conexão em outra máquina)
Fw (restringir acesso)
nano 'nome do arquivo'
sudo ufw enable (barreira de segurança)
ssh 'nome do usuário'@IP  (criar novo usuário)_
sudo poweroff (desligar)
sudo ./'nome do arquivo do script'(executar)
chmod 777 'nome do arquivo'(permição para programação)
